name: Create Branches

on:
  workflow_dispatch:
    inputs:
      system_request_number:
        description: 'System Request Number'
        required: true
        default: 'x-xxxxxx'
      production_date:
        description: 'Production Date (yyyymmdd)'
        required: true
        default: 'yyyymmdd'

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'taya99'
          git config --global user.email 'powerbomb_19@outlook.com'

      - name: Check if devlop branch exists
        id: check_devlop_branch
        run: |
          if git branch --list "devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}"; then
            echo "Branch 'devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}' already exists."
            echo "EXISTS_DEVLOP=true" >> $GITHUB_ENV
          else
            echo "Branch 'devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}' does not exist."
            echo "EXISTS_DEVLOP=false" >> $GITHUB_ENV
          fi

      - name: Create devlop branch if it does not exist
        if: env.EXISTS_DEVLOP == 'false'
        run: |
          git checkout -b "devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}"
          git push origin "devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}"

      - name: Check if release branch exists
        id: check_release_branch
        run: |
          if git branch --list "release_${{ github.event.inputs.production_date }}"; then
            echo "Branch 'release_${{ github.event.inputs.production_date }}' already exists."
            echo "EXISTS_RELEASE=true" >> $GITHUB_ENV
          else
            echo "Branch 'release_${{ github.event.inputs.production_date }}' does not exist."
            echo "EXISTS_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Create release branch if it does not exist
        if: env.EXISTS_RELEASE == 'false'
        run: |
          git checkout -b "release_${{ github.event.inputs.production_date }}" "devlop_${{ github.event.inputs.system_request_number }}_${{ github.event.inputs.production_date }}"
          git push origin "release_${{ github.event.inputs.production_date }}"
