name: Create Branches

on:
  push:
    branches:
      - main

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # リポジトリのチェックアウトステップ
        uses: actions/checkout@v2 # actions/checkoutアクションのバージョン2を使用

      - name: Set up Git # Gitのユーザー名とメールアドレスを設定するステップ
        run: |
          git config --global user.name 'taya99' # Gitのユーザー名を設定
          git config --global user.email 'powerbomb_19@outlook.com' # Gitのメールアドレスを設定

      - name: Check if devlop branch exists # devlopブランチが存在するか確認するステップ
        id: check_devlop_branch # ステップのIDを設定
        run: |
          if git show-ref --verify --quiet refs/heads/devlop; then # devlopブランチが存在するか確認
            echo "Branch 'devlop' already exists." # 存在する場合のメッセージ
            echo "::set-output name=exists::true" # 存在する場合の出力変数設定
          else
            echo "Branch 'devlop' does not exist." # 存在しない場合のメッセージ
            echo "::set-output name=exists::false" # 存在しない場合の出力変数設定
          fi

      - name: Create devlop branch if it does not exist # devlopブランチが存在しない場合に作成するステップ
        if: steps.check_devlop_branch.outputs.exists == 'false' # devlopブランチが存在しない場合のみ実行
        run: |
          git checkout -b devlop # 新しいdevlopブランチを作成
          git push origin devlop # リモートリポジトリにプッシュ

      - name: Pull devlop branch if it exists # devlopブランチが存在する場合の処理
        if: steps.check_devlop_branch.outputs.exists == 'true' # devlopブランチが存在する場合のみ実行
        run: |
          git fetch origin # リモートリポジトリをフェッチ
          git checkout devlop # devlopブランチにチェックアウト
          git pull origin devlop # リモートリポジトリのdevlopブランチをプル
          git checkout main # mainブランチにチェックアウト

      - name: Check if release branch exists # releaseブランチが存在するか確認するステップ
        id: check_release_branch # ステップのIDを設定
        run: |
          if git show-ref --verify --quiet refs/heads/release; then # releaseブランチが存在するか確認
            echo "Branch 'release' already exists." # 存在する場合のメッセージ
            echo "::set-output name=exists::true" # 存在する場合の出力変数設定
          else
            echo "Branch 'release' does not exist." # 存在しない場合のメッセージ
            echo "::set-output name=exists::false" # 存在しない場合の出力変数設定
          fi

      - name: Create release branch if it does not exist # releaseブランチが存在しない場合に作成するステップ
        if: steps.check_release_branch.outputs.exists == 'false' # releaseブランチが存在しない場合のみ実行
        run: |
          git checkout devlop # devlopブランチにチェックアウト
          git checkout -b release # 新しいreleaseブランチを作成
          git push origin release # リモートリポジトリにプッシュ

      - name: Pull release branch if it exists # releaseブランチが存在する場合の処理
        if: steps.check_release_branch.outputs.exists == 'true' # releaseブランチが存在する場合のみ実行
        run: |
          git fetch origin # リモートリポジトリをフェッチ
          git checkout release # releaseブランチにチェックアウト
          git pull origin release # リモートリポジトリのreleaseブランチをプル
          git checkout devlop # devlopブランチにチェックアウト

      - name: Check if feature branch exists # featureブランチが存在するか確認するステップ
        id: check_feature_branch # ステップのIDを設定
        run: |
          if git show-ref --verify --quiet refs/heads/feature; then # featureブランチが存在するか確認
            echo "Branch 'feature' already exists." # 存在する場合のメッセージ
            echo "::set-output name=exists::true" # 存在する場合の出力変数設定
          else
            echo "Branch 'feature' does not exist." # 存在しない場合のメッセージ
            echo "::set-output name=exists::false" # 存在しない場合の出力変数設定
          fi

      - name: Create feature branch if it does not exist # featureブランチが存在しない場合に作成するステップ
        if: steps.check_feature_branch.outputs.exists == 'false' # featureブランチが存在しない場合のみ実行
        run: |
          git checkout release # releaseブランチにチェックアウト
          git checkout -b feature # 新しいfeatureブランチを作成
          git push origin feature # リモートリポジトリにプッシュ

      - name: Pull feature branch if it exists # featureブランチが存在する場合の処理
        if: steps.check_feature_branch.outputs.exists == 'true' # featureブランチが存在する場合のみ実行
        run: |
          git fetch origin # リモートリポジトリをフェッチ
          git checkout feature # featureブランチにチェックアウト
          git pull origin feature # リモートリポジトリのfeatureブランチをプル
