name: Create Branches

on:
  push:
    branches:
      - main

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # リポジトリのチェックアウトステップ
        uses: actions/checkout@v2 # actions/checkoutアクションのバージョン2を使用

      - name: Set up Git # Gitのユーザー名とメールアドレスを設定するステップ
        run: |
          git config --global user.name 'taya99' # Gitのユーザー名を設定
          git config --global user.email 'powerbomb_19@outlook.com' # Gitのメールアドレスを設定

      - name: Check if devlop branch exists # devlopブランチが存在するか確認するステップ
        id: check_devlop_branch # ステップのIDを設定
        run: |
          if git ls-remote --heads origin devlop | grep devlop; then # devlopブランチが存在するか確認
            echo "Branch 'devlop' already exists." # 存在する場合のメッセージ
            echo "exists=true" >> $GITHUB_ENV # 存在する場合の出力変数設定
          else
            echo "Branch 'devlop' does not exist." # 存在しない場合のメッセージ
            echo "exists=false" >> $GITHUB_ENV # 存在しない場合の出力変数設定
          fi

      - name: Create devlop branch if it does not exist # devlopブランチが存在しない場合に作成するステップ
        if: env.exists == 'false' # devlopブランチが存在しない場合のみ実行
        run: |
          git checkout -b devlop # 新しいdevlopブランチを作成
          git push origin devlop # リモートリポジトリにプッシュ

      - name: Check if release branch exists # releaseブランチが存在するか確認するステップ
        id: check_release_branch # ステップのIDを設定
        run: |
          if git ls-remote --heads origin release | grep release; then # releaseブランチが存在するか確認
            echo "Branch 'release' already exists." # 存在する場合のメッセージ
            echo "exists=true" >> $GITHUB_ENV # 存在する場合の出力変数設定
          else
            echo "Branch 'release' does not exist." # 存在しない場合のメッセージ
            echo "exists=false" >> $GITHUB_ENV # 存在しない場合の出力変数設定
          fi

      - name: Create release branch if it does not exist # releaseブランチが存在しない場合に作成するステップ
        if: env.exists == 'false' # releaseブランチが存在しない場合のみ実行
        run: |
          git checkout devlop # devlopブランチにチェックアウト
          git checkout -b release # 新しいreleaseブランチを作成
          git push origin release # リモートリポジトリにプッシュ

      - name: Check if feature branch exists # featureブランチが存在するか確認するステップ
        id: check_feature_branch # ステップのIDを設定
        run: |
          if git ls-remote --heads origin feature | grep feature; then # featureブランチが存在するか確認
            echo "Branch 'feature' already exists." # 存在する場合のメッセージ
            echo "exists=true" >> $GITHUB_ENV # 存在する場合の出力変数設定
          else
            echo "Branch 'feature' does not exist." # 存在しない場合のメッセージ
            echo "exists=false" >> $GITHUB_ENV # 存在しない場合の出力変数設定
          fi

      - name: Create feature branch if it does not exist # featureブランチが存在しない場合に作成するステップ
        if: env.exists == 'false' # featureブランチが存在しない場合のみ実行
        run: |
          git checkout release # releaseブランチにチェックアウト
          git checkout -b feature # 新しいfeatureブランチを作成
          git push origin feature # リモートリポジトリにプッシュ
