name: Create Release Branch

on:
  push:
    branches:
      - main

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'taya99'
          git config --global user.email 'powerbomb_19@outlook.com'

      - name: Check if release branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/heads/release; then
            echo "Branch 'release' already exists."
            echo "::set-output name=exists::true"
          else
            echo "Branch 'release' does not exist."
            echo "::set-output name=exists::false"
          fi

      - name: Create release branch if it does not exist
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          git checkout -b release
          git push origin release
